spring.application.name=productos

spring.config.import=optional:configserver:http://localhost:8888

server.port=0

eureka.client.register-with-eureka=true
eureka.client.fetch-registry= true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


#Configuracion del nombre del servicio
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
#parametros actuator
management.endpoints.web.exposure.include=*
eureka.client.healthcheck.enabled=true
